title: Using /e/-OS on Android without Google 
short: "Data privacy is a basic human right and the current smartphone OS duopoly provides no option for customers to be safe from being exploited. In this post I'll show you a much needed alternative."
date: 27.08.2020
tags:
    - android
    - privacy
    - data
    - e
    - efoundation
