title: Using Ubuntu on a Macbook Pro 2016
short: "I haven't been happy with my Macbook and OS X for a while, so I decided to switch to Linux - this post shows how to run Ubuntu on a Macbook."
date: 22.04.2020
tags:
    - ubuntu
    - linux
    - macbook
