title: Configuring Vim for Rust development
short: "In this post, I’ll show how to configure Vim for Rust."
date: 16.06.2022
tags:
    - rust
    - vim
canonical: https://blog.logrocket.com/configuring-vim-rust-development/
