title: "Full-stack Rust: A complete tutorial with examples"
short: "In this post, I’ll show how to implement a full-stack Rust web application."
date: 26.09.2021
tags:
    - rust
    - web
    - redis
canonical: https://blog.logrocket.com/full-stack-rust-a-complete-tutorial-with-examples/
