title: Substrate blockchain development: Core concepts
short: "In this post, we'll look at the core concepts of the Rust-based Substrate blockchain development Framework."
date: 15.01.2022
tags:
    - rust
    - blockchain
    - substrate
canonical: https://blog.logrocket.com/substrate-blockchain-framework-core-concepts/
