title: JWT authentication in Rust
short: "In this post, I’ll show how to implement JWT authentication in a Rust web application."
date: 05.12.2020
tags:
    - rust
    - web
    - jwt
canonical: https://blog.logrocket.com/jwt-authentication-in-rust/
