title: Build a full-stack TypeScript app using tRPC and React
short: "In this post, I’ll show how to use tRPC to build a full-stack TypeScript app."
date: 30.06.2023
tags:
    - typescript
    - trpc
    - react
canonical: https://blog.logrocket.com/build-full-stack-typescript-app-trpc-react/
