title: TryHackMe LazyAdmin CTF Writeup
short: "This is my first CTF write-up and it's about the TryHackMe LazyAdmin CTF"
date: 03.02.2021
tags:
    - ctf
    - infosec
    - writeup
    - thm
    - tryhackme
