title: "libp2p tutorial: Build a peer-to-peer app in Rust"
short: "In this post, I’ll show how to implement a peer-to-peer application in Rust using libp2p"
date: 31.12.2020
tags:
    - rust
    - p2p
    - libp2p
    - peer2peer
canonical: https://blog.logrocket.com/libp2p-tutorial-build-a-peer-to-peer-app-in-rust/
